name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs:
  linux-x86_64-packages:
#    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/build_conda
 #       with:
 #         label: main
  windows-x86_64-packages:
#    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/build_conda
#        with:
#          label: main
  linux-arm64-packages:
#    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: 4-core-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/build_conda
#        with:
#          label: main