name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs:
  linux-x86_64-AVX512-cmake:
    runs-on: 32-core-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: ./.github/actions/build_cmake
        with:
          opt_level: avx512